org: langsdorf
app: aws-lambda-dynamo-test
service: aws-lambda-dynamo-test
frameworkVersion: "2 || 3"

custom:
  tableName: "employees-${sls:stage}"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [EmployeesTable, Arn]
  environment:
    EMPLOYEES_TABLE: ${self:custom.tableName}

functions:
  api:
    handler: main.handler
    events:
      - httpApi: "*"

resources:
  Resources:
    EmployeesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
          - AttributeName: id
            AttributeType: N
          - AttributeName: name
            AttributeType: S
          - AttributeName: age
            AttributeType: N
          - AttributeName: role
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
